import { FeedGenerator } from '../core/FeedGenerator'

export const myFeed = FeedGenerator({
    displayName: 'Freedom Planet World',
    description: 'A curated feed filtering everything Freedom planet related! May contain nsfw.',
    avatar: 'https://imgur.com/a/4e10qbA', // Replace with your hosted image link
    keywords: ['#FreedomPlanet',
        '#FreedomPlanet2',
        '#GalaxyTrailFanArt',
        '#GalaxyTrail',
        '#sashlilac',
        '#caroltea',
        '#millabasset',
        '#neerali',
        'freedom planet 2',
        'freedom planet',
        'Lilac #freedomplanet',
        'Lilac #freedomplanet2',
        'Lilac freedom planet',
        'Lilac freedom planet 2',
        'Sash Lilac',
        'Carol Tea',
        'Carol freedom planet',
        'Carol freedom planet 2',
        'Milla Basset',
        'Milla freedom planet',
        'Milla freedom planet 2',
        'Milla #freedomplanet',
        'Milla #freedomplanet2',
        'Spade #freedomplanet',
        'Spade #freedomplanet2',
        'Spade freedom planet',
        'Spade freedom planet 2',
        'Dail #freedomplanet',
        'Dail #freedomplanet2',
        'Dail freedom planet',
        'Dail freedom planet 2',
        'Neera Li',
        'Mayor Zao',
        'Merga freedom planet',
        'Merga freedom planet 2',
        'Merga #freedomplanet',
        'Merga #freedomplanet2',
        'Cordelia freedom planet',
        'Cordelia freedom planet 2',
        'Cordelia #freedomplanet',
        'Cordelia #freedomplanet2',
        'Captain Kalaw',
        'Captain Kalaw freedom planet',
        'Captain Kalaw freedom planet 2',
        'Captain Kalaw #freedomplanet',
        'Captain Kalaw #freedomplanet2',
        'Maria Notte freedom planet',
        'Maria Notte freedom planet 2',
        'Maria Notte #freedomplanet',
        'Maria Notte #freedomplanet2',
        'Red Scarves freedom planet',
        'Red Scarves freedom planet 2',
        'Corazon Tea freedom planet',
        'Corazon Tea freedom planet 2',
        'Cory freedom planet',
        'Cory freedom planet 2',
        'Cory #freedomplanet',
        'Cory #freedomplanet 2',
        'Serpentine freedom planet',
        'Serpentine freedom planet 2',
        'Serpentine #freedomplanet',
        'Serpentine #freedomplanet2',
        'Askal #freedomplanet',
        'Askal #freedomplanet2',
        'Askal freedom planet',
        'Askal freedom planet 2',
        'Magister freedom planet',
        'Magister freedom planet 2',
        'Magister #freedomplanet',
        'Magister #freedomplanet2',
        'Brevon',
        'Gong freedom planet',
        'Gong freedom planet 2',
        'Gong #freedomplanet',
        'Gong #freedomplanet2',
      ],
})
